blank_issues_enabled: false
contact_links:
  - name: 💬 Dúvidas e Bate-papo da Comunidade
    url: https://github.com/gui-ccr/grupo-estudo-cpp/discussions
    about: Use nosso fórum para tirar dúvidas e conversar sobre o projeto.